// <auto-generated />
using System;
using Event_Management_Application_Models.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Event_Management_Application_Models.Migrations
{
    [DbContext(typeof(EventManagmentDbContext))]
    [Migration("20241102170821_createTables")]
    partial class createTables
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Event_Management_Application_Models.Models.Attendee", b =>
                {
                    b.Property<int>("AttendeeID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("AttendeeID"));

                    b.Property<int>("Email")
                        .HasColumnType("int");

                    b.Property<int>("Name")
                        .HasColumnType("int");

                    b.Property<int?>("RegistrationID")
                        .HasColumnType("int");

                    b.HasKey("AttendeeID");

                    b.HasIndex("RegistrationID");

                    b.ToTable("Attendees");
                });

            modelBuilder.Entity("Event_Management_Application_Models.Models.Event", b =>
                {
                    b.Property<int>("EventID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("EventID"));

                    b.Property<int>("Date")
                        .HasColumnType("int");

                    b.Property<int>("Location")
                        .HasColumnType("int");

                    b.Property<int?>("RegistrationID")
                        .HasColumnType("int");

                    b.Property<int>("Title")
                        .HasColumnType("int");

                    b.HasKey("EventID");

                    b.HasIndex("RegistrationID");

                    b.ToTable("Events");
                });

            modelBuilder.Entity("Event_Management_Application_Models.Models.Registration", b =>
                {
                    b.Property<int>("RegistrationID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("RegistrationID"));

                    b.Property<int>("AttendeeID")
                        .HasColumnType("int");

                    b.Property<int>("EventID")
                        .HasColumnType("int");

                    b.HasKey("RegistrationID");

                    b.ToTable("Registrations");
                });

            modelBuilder.Entity("Event_Management_Application_Models.Models.Attendee", b =>
                {
                    b.HasOne("Event_Management_Application_Models.Models.Registration", null)
                        .WithMany("Attendees")
                        .HasForeignKey("RegistrationID");
                });

            modelBuilder.Entity("Event_Management_Application_Models.Models.Event", b =>
                {
                    b.HasOne("Event_Management_Application_Models.Models.Registration", null)
                        .WithMany("Events")
                        .HasForeignKey("RegistrationID");
                });

            modelBuilder.Entity("Event_Management_Application_Models.Models.Registration", b =>
                {
                    b.Navigation("Attendees");

                    b.Navigation("Events");
                });
#pragma warning restore 612, 618
        }
    }
}
